.TH "addns" "1" "06 Nov 2013" "1.0" "addns man page"
.SH NAME
addns \- update your DynDNS record
.SH SYNOPSIS
addns
.SH DESC\fBTION
addns is high level shell to update your DynDNS records.
.SH OPTIONS
.TP
\fB\-c \-\-config\fR
Configuration File (defaults to /etc/addns.db)
.TP
\fB\-x \-\-configname\fR
Configuration Label to Update
.TP
\fB\-H \-\-host\fR
Hostname(s) to update, seperated by commas
.TP
\fB\-m \-\-method\fR
Method for determining the IP address: manual, iface or webcheck
.TP
\fB\-l \-\-ip\fR
IP Address for update (manual)
.TP
\fB\-n \-\-interface\fR
Interface to obtain an IP address from
.TP
\fB\-u \-\-username\fR
Username
.TP
\fB\-p \-\-password\fR
Password
.TP
\fB\-\-detect_host\fR
Hostname or IP of the system that will validate the IP address
.TP
\fB\-s \-\-system\fR
System type: statdns, dyndns, custom
.TP
\fB\-m \-\-mx\fR
MX record host/ip
.TP
\fB\-M \-\-backup_mx\fR
Is MX record primary or backup?: yes, no, nochg
.TP
\fB\-o \-\-offline\fR
Sets host offline: yes, no
.TP
\fB\-h \-\-help\fR
Displays this help information
.TP
\fB\-v \-\-verbose\fR
Tell me more of whats going on 
.TP
\fB\-vv \-\-debug\fR
Show me everything
.TP
\fB\-d \-\-daemon\fR
Run as a daemon
.TP
\fB\-f \-\-force\fR
Force Updates
.TP
\fB\-x \-\-interval\fR
Update interval for daemon mode
.SH BUGS
No known bugs.
.SH AUTHOR
David Hasson (devel@funtaff.com)
