#!/usr/bin/perl

use Debconf::Client::ConfModule ':all';

version('2.0');

my @params = (
 	'server_host',
        'update_host',
        'username',
        'password', 
);

for my $p (@params) {
	input("medium", "addns/$p");
}


1;

